name: pipeline

on:
  push:
    branches:
      - arreglosCole

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      env:
        USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
        TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}

    - name: Print UVUS
      run: echo "davherfor"

    - name: Test with Gradle
      run:  |
        chmod +x gradlew
        ./gradlew test
      env:
        USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
        TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
  Test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo y probando el código
        run: |
          chmod +x gradlew        
          ./gradlew test
      - run: echo "davherfor"
